DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS locations;

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL,
    created_on TIMESTAMP NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    paid BOOLEAN NOT NULL DEFAULT false,
    participant_limit INT NOT NULL DEFAULT 0,
    published_on TIMESTAMP,
    state VARCHAR NOT NULL DEFAULT 'PENDING' CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED')),
    request_moderation BOOLEAN NOT NULL DEFAULT true,
    title VARCHAR(170) NOT NULL,
    initiator_id BIGINT NOT NULL
);